version: '3'
services:
  postgres:
    image: postgres:13.15-alpine3.20
    container_name: postgres-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - omilabs-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER}" ]
      interval: 30s
      timeout: 10s
      retries: 5


  mysql:
    image: mysql:latest
    container_name: inventory_db
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - omilabs-network
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 20s
      retries: 10


  sonarqube:
    image: sonarqube:community
    hostname: sonarqube
    container_name: sonarqube
    environment:
      SONAR_JDBC_URL: ${SONAR_JDBC_URL}
      SONAR_JDBC_USERNAME: ${SONAR_JDBC_USERNAME}
      SONAR_JDBC_PASSWORD: ${SONAR_JDBC_PASSWORD}
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - omilabs-network

  nexus:
    image: sonatype/nexus3
    container_name: nexus-repo
    ports:
      - "8081:8081"
    volumes:
      - nexus-data:/nexus-data
    networks:
      - omilabs-network

  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins-app
    ports:
      - "8082:8080"
      - "50000:50000"
    volumes:
      - jenkins-data:/var/jenkins_home
    networks:
      - omilabs-network
    environment:
      JAVA_OPTS: ${JAVA_OPTS}

volumes:
  jenkins-data:
  postgres-data:
  postgresql:
  mysql-data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  nexus-data:

networks:
  omilabs-network:
    driver: bridge