apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace:  inventory-deployment
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace:  inventory-deployment
  name: jenkins-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "deployments", "replicasets"]
    verbs: ["get", "list", "watch", "create", "delete", "patch", "update"]

